### PR TITLE
Project branch

### PR DESCRIPTION
**Pull request by HillaryOkello**
In this branch I created the app models which are:
* API model
* Interface model

In the API model, I set up API and used it to get data from OpenWeather.
In the Interface model, I created a list to display the weather details.

### CODE REVIEW

**Review by MkrtichSargsyan — COMMENTED** [review]
## _Status:_ Invalid submission warning

## Hello Guys


This Code Review Request will be marked as invalid in your Dashboard because the actions on Github were not set up properly.

Please make the necessary changes and submit another code review request once you are ready! :slightly_smiling_face:.


> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @HillaryOkello, great job with implementing the gitflow/GitHub flow guidelines 👍 The README file and PR is very professional 😄 The code is clean 👍 However, there are a few comments we need to address before proceeding, kindly check the comments below:
- Kindly use the right linter configuration file, remember not to make any changes to our recommended linter file. Here is a [link](https://github.com/microverseinc/linters-config/blob/master/javascript/.github/workflows/linters.yml)
- Kindly implement the toggle functionality where we can toggle between degree Celsius and Fahrenheit
- Also, for every data received, there should be a change in background for each data received

Once these are resolved, kindly submit another code review request
_Happy coding_ 👨‍💻 
[Daniel Larbi Addo](https://www.linkedin.com/mwlite/in/daniel-larbi-addo)

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @HillaryOkello  :wave:

**Great work on making the changes requested by the previous reviewer 👏** 
_You've done well implementing some of the requested changes, but there are still some which haven't addressed yet._

__However, some changes are required before this project can be approved. Please check my comments below and fix them as appropriate.__

### **Required Changes :recycle:**

- [ ] As mentioned by the last reviewer, you need to implement a toggle control to determine if the result will be shown in Celsius or Fahrenheit <em>(There are two valid solutions: students can make two different requests for the Celsius data and the Fahrenheit data OR make only one request and use math to convert it to the other unit)</em> (<a href="https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png">screenshot</a> from <a href="https://www.theodinproject.com/courses/javascript/lessons/weather-app" rel="nofollow noreferrer noopener" target="_blank">Odin</a>)


### **Optional Changes** :yellow_circle: 
_Every comment with the **OPTIONAL** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- All webpack related packages should be included in <code>package.json</code> like <code>webpack</code>, <code>webpack-cli</code>, <code>webpack-dev-server</code> etc. Also, those packages should be added as <strong>devDependencies</strong> (<a href="https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/devdep_requirement.png">screenshot</a> from <a href="https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/" rel="nofollow noreferrer noopener" target="_blank">Pathwright</a>). The only missing one is `webpack-dev-server`, as the other ones have already been added.
- Necessary run common commands like <code>build</code>, <code>development</code> should be in <code>package.json</code> inside `scripts'. Here is a basic example (<a href="https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/scripts_requirement.png">screenshot</a> from <a href="https://microve- [ ] rse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/" rel="nofollow noreferrer noopener" target="_blank">Pathwright</a>)</li>
</ul>
<pre class="code highlight js-syntax-highlight language-javascript white" v-pre="true" lang="javascript"><code><span id="LC1" class="line" lang="javascript"><span class="dl">"</span><span class="s2">scripts</span><span class="dl">"</span><span class="p">:</span> <span class="p">{</span></span>
<span id="LC2" class="line" lang="javascript">    <span class="dl">"</span><span class="s2">dev</span><span class="dl">"</span><span class="p">:</span> <span class="dl">"</span><span class="s2">webpack --mode development</span><span class="dl">"</span><span class="p">,</span></span>
<span id="LC3" class="line" lang="javascript">    <span class="dl">"</span><span class="s2">build</span><span class="dl">"</span><span class="p">:</span> <span class="dl">"</span><span class="s2">webpack --mode production</span><span class="dl">"</span><span class="p">,</span></span>
<span id="LC4" class="line" lang="javascript">    <span class="dl">"</span><span class="s2">start</span><span class="dl">"</span><span class="p">:</span> <span class="dl">"</span><span class="s2">webpack-dev-server --mode development --open</span><span class="dl">"</span> <span class="c1">// optional</span></span>
<span id="LC5" class="line" lang="javascript">  <span class="p">},</span></span></code></pre>

* * *
**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.**

*Feel free to leave any questions or comments in the PR thread if something is not 100% clear.*

_**Please make the required changes and submit another review request when you are done.**_

* * *
Cheers, 
**Taofeek Olalere**
__Happy coding :smiley:__

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @HillaryOkello, great job working on adding the button to change from degree Celcius to Fahrenheit, however, to change the Fahrenheit back to degree Celcius is a problem which we need to fix. In the previous review we were given two options to solve the toggle functionality, kindly go back and implement it before requesting another code review request :smile: 

**N/B**: This requirement escaped me on the first review, let us update the script so we can run the following commands, "npm run dev", "nom run build", etc
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production"
}
```
[optional]
- Kindly remember to update the live link

_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/mwlite/in/daniel-larbi-addo)

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi Hillary Okello :wave: 

* [ ] Update the **live link** in the current branch of your readme. Using the link you provided, when I preview the weather app, it does not have the styles nor the button to toggle between the temperature units, compared to what I get when I run it locally. 

* [ ]   [**Observation**] Remember to work on the button that toggles between **Celsius** and **Fahrenheit**. It remains only in Fahrenheit. It should change between the two units depending on which unit to display.

### Have a great day :slightly_smiling_face: 

#### ``` Uchechukwu Henry Inyama ```

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Pull request merged**
